export const FETCH_ARTICLE_LIST = 'FETCH_ARTICLE_LIST';
export const FETCH_ARTICLE_LIST_SUCCEEDED = 'FETCH_ARTICLE_LIST_SUCCEEDED';
export const FETCH_ARTICLE_LIST_FAILED = 'FETCH_ARTICLE_LIST_FAILED';

export const FETCH_ARTICLE_DETAIL = 'FETCH_ARTICLE_DETAIL';
export const FETCH_ARTICLE_DETAIL_SUCCEEDED = 'FETCH_ARTICLE_DETAIL_SUCCEEDED';
export const FETCH_ARTICLE_DETAIL_FAILED = 'FETCH_ARTICLE_DETAIL_FAILED';

export const CLEAR_ARTICLE_DETAIL = 'CLEAR_ARTICLE_DETAIL';

export const SWITCH_SELECTED_INDEX = 'SWITCH_SELECTED_INDEX';
